"""Add emoji to mood_entries table

Revision ID: 198ab2d8f701
Revises: 3f419a137b79
Create Date: 2025-08-18 01:17:28.887545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '198ab2d8f701'
down_revision: Union[str, Sequence[str], None] = '3f419a137b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mood_entries', sa.Column('emoji', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mood_entries', 'emoji')
    # ### end Alembic commands ###
