"""Add reasoning_text to mood_entries table

Revision ID: 3f419a137b79
Revises: 3ecbaf2f66b0
Create Date: 2025-08-18 00:48:03.050781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f419a137b79'
down_revision: Union[str, Sequence[str], None] = '3ecbaf2f66b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mood_entries', sa.Column('reasoning_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mood_entries', 'reasoning_text')
    # ### end Alembic commands ###
